version: "3"
services:
  printerbot:
    image: ghcr.io/bitbyt3r/printerbot:main
    build: .
    restart: always
    env_file:
     - .env
    volumes:
     - ./:/app
    command: python printerbot.py
  cups:
    image: olbat/cupsd
    ports:
      - 631:631
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ./cupsd.conf:/etc/cups/cupsd.conf
      - printers:/etc/cups/printers.conf
    restart: always
volumes:
  printers: